site_name: UI Tween
site_description: Documentation UI Tween by CommanderFoo in Community Content

docs_dir: docs
extra_css:
  - styles/extra.css
theme:
  custom_dir: mkdocs-material/material
  language: en
  font:
    text: Roboto
    code: Monospace
  palette:
    - scheme: slate
      accent: orange
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - toc.integrate
    - navigation.expand
  icon:
    repo: fontawesome/brands/github
  
nav:
  - UI Tween:
    - Home: index.md
    - quick-start.md
    - examples.md
    - events.md
    - easings.md
    - functions.md
    - curves.md
    - credits.md

  - Core Games:
    - https://coregames.com

  - Twitter:
    - https://twitter.com/PIXELDEPTH

  - GitHub:
    - https://pixeldepth.net

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences
  - markdown.extensions.codehilite:
      guess_lang: false
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - lightgallery
  - attr_list
